# Assignment Part One
You are free choose whether to solve the following exercises in MQL or to write the queries in python using <a href='https://pymongo.readthedocs.io/en/stable/'>pymongo</a>

In [1]:
#!python3
import pymongo
from pymongo import MongoClient
#import dnspython
from tabulate import tabulate
import ssl
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt

In [2]:
client = MongoClient('mongodb+srv://student:nRfKfRqEtgWvznFD@cluster0.gu4ru.mongodb.net')
db = client.get_database('sample_airbnb')
rbnb = db.listingsAndReviews.find()
rbnb_df = pd.DataFrame(rbnb)

## Airbnb Dataset

What is the name of the listing in the sample_airbnb.listingsAndReviews dataset
that accommodates more than 6 people and has exactly 50 reviews

In [3]:
rbnb_df[(rbnb_df['accommodates']>6) & ([len(x)==50 for x in rbnb_df['reviews']])]

#[len(x)==50 for x in rbnb_df['reviews']]

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,host,address,availability,review_scores,reviews,security_deposit,cleaning_fee,weekly_price,monthly_price,reviews_per_month
4525,4294289,https://www.airbnb.com/rooms/4294289,Sunset Beach Lodge Retreat,"Large 3 bedrooms, 2 bathrooms with Office Spac...",This amazing lodge style home is one of da kin...,"Large 3 bedrooms, 2 bathrooms with Office Spac...",Sunset Beach area is one of the prestigious pl...,(Phone number hidden by Airbnb),,The entire upstairs unit. Parking Lot.,...,"{'host_id': '13508451', 'host_url': 'https://w...","{'street': 'Haleiwa, HI, United States', 'subu...","{'availability_30': 6, 'availability_60': 28, ...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '31113473', 'date': 2015-05-02 04:00:...",500.00,300.00,NaN,NaN,NaN

Using the sample_airbnb.listingsAndReviews collection find out how many
documents have the "property_type" "House", and include "Changing table" as
one of the "amenities"?

In [4]:

rbnb_df[([('Changing table' in x) for x in rbnb_df['amenities']])& (rbnb_df['property_type'] == 'House')]

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,host,address,availability,review_scores,reviews,security_deposit,cleaning_fee,weekly_price,monthly_price,reviews_per_month
1080,15893952,https://www.airbnb.com/rooms/15893952,"Modern, Quiet Semi stroll to Manly Beach",Our home is just a short walk away from all th...,Guests are able to use the whole property incl...,Our home is just a short walk away from all th...,"Our place is close to Manly Beach, shops, rest...",,"Our house is only a short walk to the beach, r...",,...,"{'host_id': '85391052', 'host_url': 'https://w...","{'street': 'Manly, NSW, Australia', 'suburb': ...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '116696041', 'date': 2016-12-02 05:00...",500.00,100.00,NaN,NaN,NaN
1096,15997148,https://www.airbnb.com/rooms/15997148,Huge kid-friendly Brooklyn home with parking/p...,Our place is close to J train to lower Manhatt...,,Our place is close to J train to lower Manhatt...,,,,,...,"{'host_id': '200060', 'host_url': 'https://www...","{'street': 'Brooklyn, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '115682030', 'date': 2016-11-26 05:00...",NaN,NaN,NaN,NaN,NaN
1106,16029413,https://www.airbnb.com/rooms/16029413,"Bundeena Base Art House, Sea View with Heated ...","With fabulous views, overlooking the sea, Bund...",Please note that the airbnb site does not show...,"With fabulous views, overlooking the sea, Bund...","Untouched beaches, the Royal National Park, cu...",Please be aware that for the safety of everyon...,"Once in Bundeena, you really don't need a car ...","We prefer someone to be here when you arrive, ...",...,"{'host_id': '104281282', 'host_url': 'https://...","{'street': 'Bundeena, NSW, Australia', 'suburb...","{'availability_30': 22, 'availability_60': 43,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '130150920', 'date': 2017-02-04 05:00...",500.00,120.00,NaN,NaN,NaN
1152,16253247,https://www.airbnb.com/rooms/16253247,Gorgeous Remodeled Modern Home w/ Beach Across...,Newly remodeled! Gorgeous home with fully remo...,Guests love: - Mid Century Modern Main house: ...,Newly remodeled! Gorgeous home with fully remo...,Kailua-Kona is a quaint town on the west coast...,Watching the sunset on the beach across the st...,Proximity to Airports: Surf Temple is just twe...,Guests will have access to the entire house! T...,...,"{'host_id': '106070244', 'host_url': 'https://...","{'street': 'Kailua-Kona, HI, United States', '...","{'availability_30': 5, 'availability_60': 11, ...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '124406978', 'date': 2017-01-01 05:00...",100.00,200.00,NaN,NaN,NaN
1251,16885508,https://www.airbnb.com/rooms/16885508,Private Family Retreat with Spa & Pool,"Light, airy open plan holiday home with spacio...",Baby gates available for children's rooms. No ...,"Light, airy open plan holiday home with spacio...",Our neighbourhood is always very quiet so no o...,Please note we have done a few renovations rec...,There is always lots of street parking availab...,Everywhere except the back garden below the de...,...,"{'host_id': '103281975', 'host_url': 'https://...","{'street': 'Saint Ives, NSW, Australia', 'subu...","{'availability_30': 0, 'availability_60': 15, ...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '194980560', 'date': 2017-09-17 04:00...",500.00,85.00,NaN,NaN,NaN
1703,19572281,https://www.airbnb.com/rooms/19572281,Comfortable bedroom close to the airport - Porto,"Quarto muito confortável em moradia, com TV po...","Os hóspedes podem usar o quarto, casa de banho...","Quarto muito confortável em moradia, com TV po...","Zona residencial muito tranquila, com acesso a...",,"Estacionamento fácil na via pública, em frente...",Livre acesso à cozinha.,...,"{'host_id': '88573374', 'host_url': 'https://w...","{'street': 'Vila Nova da Telha, Porto, Portuga...","{'availability_30': 15, 'availability_60': 35,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '182392512', 'date': 2017-08-14 04:00...",0.00,0.00,NaN,NaN,NaN
1947,20206764,https://www.airbnb.com/rooms/20206764,Awesome 2-storey home Bronte Beach next to Bondi!,Prestige full time holiday stay in North Bront...,* Master quarters over sized room with plush q...,Prestige full time holiday stay in North Bront...,Favaloso great cafe around the corner Famous c...,"Quiet neighbourhood, no events or parties allowed",Walking Uber or Taxi Bus stop 1-2min walk,Entire place as described,...,"{'host_id': '10462547', 'host_url': 'https://w...","{'street': 'Bronte, NSW, Australia', 'suburb':...","{'availability_30': 0, 'availability_60': 5, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '194394612', 'date': 2017-09-16 04:00...",750.00,95.00,NaN,NaN,NaN
2292,22005432,https://www.airbnb.com/rooms/22005432,Beautiful Bondi Beachside Home,"This beautiful sun-filled, renovated and fully...",This place is newly renovated family home. We ...,"This beautiful sun-filled, renovated and fully...",Bondi Beach is a special place. It has an incr...,We might be able to organise all day parking c...,The bus stop is a 1 minute walk. There is on ...,"In addition to great quality linen, we provide...",...,"{'host_id': '1879921', 'host_url': 'https://ww...","{'street': 'Bondi Beach, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 10, ...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '223835129', 'date': 2018-01-01 05:00...",1000.00,250.00,NaN,NaN,NaN
2426,22396955,https://www.airbnb.com/rooms/22396955,Pause_Oporto,This house in a renovated building from the en...,This house retains its original structure. As ...,This house in a renovated building from the en...,The house is located in a residential zone wit...,There’s a wide range of transports near the ho...,There’s a wide range of transports near the ho...,The house is all available for the private use...,...,"{'host_id': '163147652', 'host_url': 'https://...","{'street': 'Porto, Porto, Portugal', 'suburb':...","{'availability_30': 19, 'availability_60': 41,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '247693704', 'date': 2018-03-29 04:00...",0.00,20.00,NaN,NaN,NaN
4517,3963635,https://www.airbnb.com/rooms/3963635,"A 2-story, 2-bedroom house - 20min to Downtown","This 2-bedroom, 2-floor home is the perfect ho...","A sweet 2-bedroom, two-floor apartment in a pr...","This 2-bedroom, 2-floor home is the perfect ho...",Bedford–Stuyvesant (colloquially known as Bed-...,"There is a cat, Gigi, who lives on the premise...",The apartment is in walking distance to a seve...,Hosts Pervaiz & Laena live in the apartment wi...,...,"{'host_id': '20543178', 'host_url': 'https://w...","{'street': 'Brooklyn , NY, United States', 'su...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '40264452', 'date': 2015-07-29 04:00:...",0.00,100.00,NaN,NaN,NaN
4786,5307830,https://www.airbnb.com/rooms/5307830,⭐️Ocean/City Views⭐️Van Included⭐️Hot Tub⭐️3 Bath,E komo mai [Welcome]! ￫ Solar-panel powered h...,￫ Is this your first booking on Airbnb? Use th...,E komo mai [Welcome]! ￫ Solar-panel powered h...,Here are my personal recommendations: airbnb.c...,*State of Hawaii Taxes - General Excise Tax (...,"We have our own fleet of vehicles, which inclu...",Entire space is included in this rental. Pleas...,...,"{'host_id': '24671259', 'host_url': 'https://w...","{'street': 'Honolulu, HI, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '198007203', 'date': 2017-09-27 04:00...",300.00,495.00,NaN,NaN,NaN

What room types are present in the sample_airbnb.listingsAndReviews collection?

In [5]:
np.unique(rbnb_df['room_type'])

array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)

## Mflix Dataset

(following exercise may be easier in python) 
Our movies dataset has a lot of different documents, some with more convoluted titles than
others. 
Find the count of the number of movies that have a title composed of one word. 
To clarify, "Cinderella" and "3-25" should count, where as "Cast Away" would not. 

You may want to take look into the `$split` String expression and the `$size` Array expression

* https://docs.mongodb.com/manual/reference/operator/aggregation/split/
* https://docs.mongodb.com/manual/reference/operator/aggregation/size/
* https://database.guide/mongodb-split/
* https://pymongo.readthedocs.io/en/stable/examples/aggregation.html

In [6]:
db = client.get_database('sample_mflix')
movies = db.movies.find()
movies_df = pd.DataFrame(movies)
movies_df.head()

,_id,plot,genres,runtime,cast,num_mflix_comments,title,fullplot,languages,released,...,awards,lastupdated,year,imdb,countries,type,tomatoes,poster,writers,metacritic
0,573a1390f29313caabcd446f,"A greedy tycoon decides, on a whim, to corner ...","[Short, Drama]",14.0,"[Frank Powell, Grace Henderson, James Kirkwood...",1,A Corner in Wheat,"A greedy tycoon decides, on a whim, to corner ...",[English],1909-12-13,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-13 00:46:30.660000000,1909,"{'rating': 6.6, 'votes': 1375, 'id': 832}",[USA],movie,"{'viewer': {'rating': 3.6, 'numReviews': 109, ...",NaN,NaN,NaN
1,573a1390f29313caabcd4803,"Cartoon figures announce, via comic strip ball...","[Animation, Short, Comedy]",7.0,[Winsor McCay],0,"Winsor McCay, the Famous Cartoonist of the N.Y...",Cartoonist Winsor McCay agrees to create a lar...,[English],1911-04-08,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-29 01:09:03.030000000,1911,"{'rating': 7.3, 'votes': 1034, 'id': 1737}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 89, '...",https://m.media-amazon.com/images/M/MV5BYzg2Nj...,"[Winsor McCay (comic strip ""Little Nemo in Slu...",NaN
2,573a1390f29313caabcd4eaf,"A woman, with the aid of her police officer sw...","[Crime, Drama]",88.0,"[Jane Gail, Ethel Grandin, William H. Turner, ...",1,Traffic in Souls,NaN,[English],1913-11-24,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-15 02:07:14.247000000,1913,"{'rating': 6.0, 'votes': 371, 'id': 3471}",[USA],movie,"{'viewer': {'rating': 3.0, 'numReviews': 85, '...",https://m.media-amazon.com/images/M/MV5BYzk0YW...,NaN,NaN
3,573a1390f29313caabcd516c,Original advertising for the film describes it...,"[Drama, History]",65.0,"[Stanley Hunt, Sarah Constance Smith Hunt, Mrs...",1,In the Land of the Head Hunters,NaN,[English],1914-12-07,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-16 12:11:37.770000000,1914,"{'rating': 5.8, 'votes': 223, 'id': 4150}",[USA],movie,"{'viewer': {'rating': 2.7, 'numReviews': 64, '...",https://m.media-amazon.com/images/M/MV5BMjE3Mj...,[Edward S. Curtis (story)],NaN
4,573a1390f29313caabcd5293,Young Pauline is left a lot of money when her ...,[Action],199.0,"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",0,The Perils of Pauline,Young Pauline is left a lot of money when her ...,[English],1914-03-23,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-12 00:01:18.647000000,1914,"{'rating': 7.6, 'votes': 744, 'id': 4465}",[USA],movie,"{'viewer': {'rating': 2.8, 'numReviews': 9}, '...",https://m.media-amazon.com/images/M/MV5BMzgxOD...,"[Charles W. Goddard (screenplay), Basil Dickey...",NaN

In [7]:
movies_df[movies_df.loc[:,'title'].str.contains('.\s.') == False]

,_id,plot,genres,runtime,cast,num_mflix_comments,title,fullplot,languages,released,...,awards,lastupdated,year,imdb,countries,type,tomatoes,poster,writers,metacritic
13,573a1391f29313caabcd7616,"Salome, the daughter of Herodias, seduces her ...","[Biography, Drama, History]",72.0,"[Mitchell Lewis, Alla Nazimova, Rose Dione, Ea...",0,Salomè,"Salome, the daughter of Herodias, seduces her ...",NaN,1923-02-15,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-04-26 00:03:19.913000000,1922,"{'rating': 6.6, 'votes': 466, 'id': 13571}",[USA],movie,"{'viewer': {'rating': 3.9, 'numReviews': 310, ...",https://m.media-amazon.com/images/M/MV5BMjA0MT...,"[Oscar Wilde (play), Natacha Rambova (scenario)]",NaN
23,573a1391f29313caabcd8780,"A salesgirl with plenty of ""it"" (sex appeal) p...","[Comedy, Romance]",72.0,"[Clara Bow, Antonio Moreno, William Austin, Pr...",1,It,Shopgirl Betty Lou has designs on Cyrus Waltha...,NaN,1927-02-15,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-06 00:01:15.977000000,1927,"{'rating': 7.5, 'votes': 2025, 'id': 18033}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 4599,...",https://m.media-amazon.com/images/M/MV5BMTAxNT...,"[Elinor Glyn (story), Hope Loring (screen play...",NaN
24,573a1391f29313caabcd8945,A married farmer falls under the spell of a sl...,"[Drama, Romance]",94.0,"[George O'Brien, Janet Gaynor, Margaret Living...",0,Sunrise,"In this fable-morality subtitled ""A Song of Tw...",NaN,1927-11-04,...,"{'wins': 5, 'nominations': 1, 'text': 'Won 3 O...",2015-09-12 00:26:13.493000000,1927,"{'rating': 8.4, 'votes': 24480, 'id': 18455}",[USA],movie,"{'viewer': {'rating': 4.4, 'numReviews': 9134,...",https://m.media-amazon.com/images/M/MV5BNDVkYm...,"[Carl Mayer (scenario), Hermann Sudermann (fro...",NaN
26,573a1391f29313caabcd8979,Among the residents of a theatrical boarding h...,"[Comedy, Drama]",60.0,"[Nancy Nash, Earle Foxe, Grant Withers, Lydia ...",3,Upstream,Among the residents of a theatrical boarding h...,[English],1927-01-30,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-06-20 00:36:05.633000000,1927,"{'rating': 6.2, 'votes': 179, 'id': 18530}",[USA],movie,"{'viewer': {'rating': 3.5, 'numReviews': 6}, '...",NaN,"[Randall Faye, Wallace Smith (story)]",NaN
27,573a1391f29313caabcd89aa,"Two young men, one rich, one middle class, who...","[Drama, Romance, War]",144.0,"[Clara Bow, Charles 'Buddy' Rogers, Richard Ar...",1,Wings,Two young men fall in love with the same same ...,[English],1929-01-05,...,"{'wins': 5, 'nominations': 1, 'text': 'Won 2 O...",2015-09-02 00:36:34.413000000,1927,"{'rating': 7.8, 'votes': 7196, 'id': 18578}",[USA],movie,"{'viewer': {'rating': 3.8, 'numReviews': 3316,...",https://m.media-amazon.com/images/M/MV5BYTI1Yj...,"[John Monk Saunders (story), Hope Loring (scre...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23506,573a13f6f29313caabde568a,"The ""manager"" of a pancake stall finds himself...",[Drama],113.0,"[Kirin Kiki, Miyoko Asada, Etsuko Ichihara, Mi...",1,An,"The ""manager"" of a pancake stall finds himself...",[Japanese],2015-05-30,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-27 00:14:54.743000000,2015,"{'rating': 7.4, 'votes': 172, 'id': 4298958}","[Japan, France, Germany]",movie,NaN,https://m.media-amazon.com/images/M/MV5BMjIxOT...,"[Durian Sukegawa (based on the novel by), Naom...",NaN
23507,573a13f6f29313caabde5900,"When the ship's owner goes bankrupt, the crew ...",[Drama],104.0,"[Nadir Saribacak, Hakan Karsak, Kadir Cermik, ...",2,Ivy,"When the ship's owner goes bankrupt, the crew ...",[Turkish],2015-01-26,...,"{'wins': 1, 'nominations': 3, 'text': '1 win &...",2015-08-05 00:14:34.537000000,2015,"{'rating': 7.6, 'votes': 48, 'id': 4309356}","[Turkey, Germany]",movie,NaN,https://m.media-amazon.com/images/M/MV5BMTUyNz...,[Tolga Karaèelik],NaN
23515,573a13f7f29313caabde74cd,NaN,[Drama],127.0,"[Catherine Frot, Andrè Marcon, Denis Mpunga, M...",0,Marguerite,NaN,[French],NaT,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-09-17 04:45:55.677000000,2015,"{'rating': 7.3, 'votes': 98, 'id': 4428788}","[Czech Republic, Belgium, France]",movie,NaN,NaN,"[Xavier Giannoli, Marcia Romano (collaborating...",NaN
23518,573a13f9f29313caabde9a81,NaN,NaN,71.0,"[Fernando Bolaèos, Kattia Gonzèlez]",0,Viaje,NaN,[Spanish],2015-04-16,...,"{'wins': 0, 'nominations': 2, 'text': '2 nomin...",2015-08-22 01:09:37.843000000,2015,"{'rating': 6.9, 'votes': 28, 'id': 4543804}",[Costa Rica],movie,NaN,NaN,NaN,NaN
23525,573a13faf29313caabdeba84,A man who supposley killed his family hides at...,[Thriller],111.0,"[Seong-woo Bae, Eui-sung Kim, Ah-sung Ko, Sung...",1,Office,Kim Byong-gook works as section chief in big b...,[Korean],2015-08-27,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-14 00:12:17.177000000,2015,"{'rating': 5.7, 'votes': 37, 'id': 4682562}",[South Korea],movie,NaN,https://m.media-amazon.com/images/M/MV5BZTA0ND...,NaN,NaN

Pick all movies that match following criteria: 

* imdb.rating is at least 7
* genres does not contain "Crime" or "Horror"
* rated is either "PG" or "G"

In [8]:

rate_bool =[]
for i in [c['rating'] for c in [x for x in movies_df.loc[:,'imdb']]]:
    if i == '':
        i=0
    rate_bool.append(i>7)

genre_bool = []
for movie in [mov for mov in movies_df.loc[:,'genres']]:
    if type(movie) == float:
        movie =[]
    genre_bool.append(('Horror' in movie) | ('Crime' in movie))


rated_bool = [(m in ['PG','G']) for m in movies_df.loc[:,'rated']]

In [9]:
movies_df[np.multiply(np.multiply(rate_bool,genre_bool),rated_bool)]

,_id,plot,genres,runtime,cast,num_mflix_comments,title,fullplot,languages,released,...,awards,lastupdated,year,imdb,countries,type,tomatoes,poster,writers,metacritic
775,573a1393f29313caabcde008,"Two young men strangle their ""inferior"" classm...","[Crime, Drama, Thriller]",80.0,"[Dick Hogan, John Dall, Farley Granger, Edith ...",1,Rope,Brandon and Philip are two young men who share...,[English],1948-08-28,...,"{'wins': 0, 'nominations': 3, 'text': '3 nomin...",2015-09-06 00:54:06.103000000,1948,"{'rating': 8.0, 'votes': 88618, 'id': 40746}",[USA],movie,"{'viewer': {'rating': 4.0, 'numReviews': 38062...",https://m.media-amazon.com/images/M/MV5BYWFjMD...,"[Hume Cronyn (adapted by), Patrick Hamilton (f...",NaN
1146,573a1394f29313caabcdf81b,An ex-tennis pro carries out a plot to murder ...,"[Crime, Thriller]",105.0,"[Ray Milland, Grace Kelly, Robert Cummings, Jo...",0,Dial M for Murder,"In London, wealthy Margot Mary Wendice had a b...",[English],1954-05-29,...,"{'wins': 4, 'nominations': 2, 'text': 'Nominat...",2015-09-04 00:36:36.117000000,1954,"{'rating': 8.2, 'votes': 93546, 'id': 46912}",[USA],movie,"{'viewer': {'rating': 3.9, 'numReviews': 37269...",https://m.media-amazon.com/images/M/MV5BOWIwOD...,"[Frederick Knott (screen play), Frederick Knot...",NaN
2174,573a1395f29313caabce2ffd,A man refuses to conform to life in a rural pr...,"[Crime, Drama]",126.0,"[Paul Newman, George Kennedy, J.D. Cannon, Lou...",0,Cool Hand Luke,"Luke Jackson is a cool, gutsy prisoner in a So...",[English],1967-11-01,...,"{'wins': 6, 'nominations': 6, 'text': 'Won 1 O...",2015-09-04 00:33:43.757000000,1967,"{'rating': 8.2, 'votes': 109282, 'id': 61512}",[USA],movie,"{'viewer': {'rating': 4.1, 'numReviews': 62369...",https://m.media-amazon.com/images/M/MV5BOWFlNz...,"[Donn Pearce (screenplay), Frank Pierson (scre...",NaN
2256,573a1395f29313caabce321b,"In 1942, in Warsaw, a Polish prostitute is mur...","[Crime, Drama, Mystery]",148.0,"[Peter O'Toole, Omar Sharif, Tom Courtenay, Do...",1,The Night of the Generals,"In 1942, in Warsaw, a Polish prostitute is mur...","[English, Italian, Spanish, French]",1967-02-24,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-22 00:17:45.890000000,1967,"{'rating': 7.4, 'votes': 4350, 'id': 62038}","[UK, France]",movie,"{'viewer': {'rating': 3.7, 'numReviews': 981, ...",https://m.media-amazon.com/images/M/MV5BNTA4Nz...,"[Joseph Kessel (adapted for the screen by), Pa...",NaN
2412,573a1396f29313caabce443f,One of the first films about the mafia occurre...,"[Crime, Drama]",101.0,"[Franco Nero, Martin Balsam, Marilè Tolo, Clau...",0,Confessions of a Police Captain,One of the first films about the mafia occurre...,[Italian],1971-03-26,...,"{'wins': 2, 'nominations': 1, 'text': '2 wins ...",2015-08-13 00:10:10.397000000,1971,"{'rating': 7.2, 'votes': 704, 'id': 66940}",[Italy],movie,"{'viewer': {'rating': 3.5, 'numReviews': 141, ...",https://m.media-amazon.com/images/M/MV5BMTJiNT...,"[Damiano Damiani (story), Fulvio Gicca Palli (...",NaN
2468,573a1396f29313caabce4efc,Released from prison apparently under a New Ye...,"[Comedy, Crime]",90.0,"[Lino Ventura, Franèoise Fabian, Charles Gèrar...",0,Happy New Year,Released from prison apparently under a New Ye...,[French],1973-04-13,...,"{'wins': 4, 'nominations': 1, 'text': '4 wins ...",2015-08-14 01:00:06.003000000,1973,"{'rating': 7.3, 'votes': 829, 'id': 69815}","[France, Italy]",movie,"{'viewer': {'rating': 3.9, 'numReviews': 274, ...",https://m.media-amazon.com/images/M/MV5BYzAyOT...,"[Claude Lelouch (original scenario), Pierre Uy...",NaN
2482,573a1396f29313caabce50f1,A year after Sheila is killed in a hit-and-run...,"[Crime, Drama, Mystery]",120.0,"[Richard Benjamin, Dyan Cannon, James Coburn, ...",0,The Last of Sheila,Sheila is killed in a hit-and-run car accident...,"[English, French]",1973-06-14,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-02 00:00:53.320000000,1973,"{'rating': 7.4, 'votes': 3191, 'id': 70291}",[USA],movie,"{'viewer': {'rating': 3.8, 'numReviews': 1361,...",https://m.media-amazon.com/images/M/MV5BNzM3OD...,"[Stephen Sondheim, Anthony Perkins]",NaN
2499,573a1396f29313caabce34c4,"An all guts, no glory San Francisco cop become...","[Action, Crime, Mystery]",114.0,"[Steve McQueen, Robert Vaughn, Jacqueline Biss...",0,Bullitt,High profile San Francisco Police Lieutenant F...,[English],1968-10-17,...,"{'wins': 10, 'nominations': 6, 'text': 'Won 1 ...",2015-09-07 00:08:54.533000000,1968,"{'rating': 7.5, 'votes': 43049, 'id': 62765}",[USA],movie,"{'viewer': {'rating': 3.8, 'numReviews': 39414...",https://m.media-amazon.com/images/M/MV5BYTQwNj...,"[Alan Trustman (screenplay), Harry Kleiner (sc...",NaN
2625,573a1396f29313caabce4f40,"A man, his wife, and their friend, stage a blo...","[Action, Crime, Drama]",111.0,"[Walter Matthau, Joe Don Baker, Felicia Farr, ...",1,Charley Varrick,Charley Varrick and his friends rob a small to...,[English],NaT,...,"{'wins': 0, 'nominations': 2, 'text': 'Won 1 B...",2015-09-12 00:01:38.777000000,1973,"{'rating': 7.5, 'votes': 7035, 'id': 69865}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 3047,...",https://m.media-amazon.com/images/M/MV5BNDk2MT...,"[John Reese (novel), Howard Rodman (screenplay...",NaN
2634,573a1396f29313caabce518f,"During the Great Depression, a con man finds h...","[Comedy, Crime, Drama]",102.0,"[Ryan O'Neal, Tatum O'Neal, Madeline Kahn, Joh...",0,Paper Moon,"Adapted from the novel, ""Addie Pray"" (1971) by...",[English],1973-05-09,...,"{'wins': 8, 'nominations': 10, 'text': 'Won 1 ...",2015-09-02 00:24:07.990000000,1973,"{'rating': 8.2, 'votes': 21470, 'id': 70510}",[USA],movie,"{'viewer': {'rating': 4.1, 'numReviews': 11037...",https://m.media-amazon.com/images/M/MV5BOWVmYz...,"[Joe David Brown (novel), Alvin Sargent (scree...",NaN
2639,573a1396f29313caabce5265,"In Chicago in September 1936, a young con man ...","[Comedy, Crime, Drama]",129.0,"[Paul Newman, Robert Redford, Robert Shaw, Cha...",0,The Sting,"When a mutual friend is killed by a mob boss, ...",[English],1973-12-26,...,"{'wins': 17, 'nominations': 6, 'text': 'Won 7 ...",2015-09-05 00:01:35.660000000,1973,"{'rating': 8.4, 'votes': 157525, 'id': 70735}",[USA],movie,"{'viewer': {'rating': 4.1, 'numReviews': 60591...",https://m.media-amazon.com/images/M/MV5BZWNmOD...,[David S. Ward],NaN
2798,573a1396f29313caabce4ed3,An impressionable teen girl from a dead-end to...,"[Crime, Drama]",94.0,"[Martin Sheen, Sissy Spacek, Warren Oates, Ram...",1,Badlands,It's the late 1950s. Mid-twenty-something Kit ...,"[English, Spanish]",1974-01-05,...,"{'wins': 4, 'nominations': 0, 'text': 'Nominat...",2015-08-18 00:13:05.093000000,1973,"{'rating': 7.9, 'votes': 42455, 'id': 69762}",[USA],movie,"{'viewer': {'rating': 4.1, 'numReviews': 24817...",https://m.media-amazon.com/images/M/MV5BMDcxNj...,[Terrence Malick],90.0
2803,573a1396f29313caabce4f7f,"A professional assassin codenamed ""Jackal"" plo...","[Crime, Drama, Thriller]",143.0,"[Edward Fox, Terence Alexander, Michel Auclair...",0,The Day of the Jackal,It is the early 60s in France. The remaining s...,"[English, Italian, French]",1973-07-30,...,"{'wins': 2, 'nominations': 10, 'text': 'Nomina...",2015-08-21 00:42:34.783000000,1973,"{'rating': 7.8, 'votes': 27372, 'id': 69947}","[UK, France]",movie,"{'viewer': {'rating': 3.9, 'numReviews': 8717,...",https://m.media-amazon.com/images/M/MV5BNjZmMW...,"[Frederick Forsyth (book), Kenneth Ross (scree...",NaN
2804,573a1396f29313caabce4fe6,A short Arizona motorcycle cop gets his wish a...,"[Crime, Drama, Mystery]",114.0,"[Robert Blake, Billy Green Bush, Mitchell Ryan...",0,Electra Glide in Blue,A short Arizona motorcycle cop gets his wish a...,[English],1973-10-04,...,"{'wins': 0, 'nominations': 2, 'text': 'Nominat...",2015-08-13 00:28:07.723000000,1973,"{'rating': 7.2, 'votes': 3355, 'id': 70022}",[USA],movie,"{'viewer': {'rating': 3.6, 'numReviews': 2327,...",https://m.media-amazon.com/images/M/MV5BZWU2ZT...,"[Robert Boris (screenplay), Robert Boris (stor...",NaN
2956,573a1396f29313caabce4a94,A recently released ex-con and his loyal wife ...,"[Action, Crime, Thriller]",122.0,"[Steve McQueen, Ali MacGraw, Ben Johnson, Sall...",0,The Getaway,Doc McCoy has been granted parole. The catch i...,"[English, Spanish]",1972-12-13,...,"{'wins': 2, 'nominations': 0, 'text': 'Nominat...",2015-09-12 00:27:28.090000000,1972,"{'rating': 7.5, 'votes': 19487, 'id': 68638}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 9479,...",https://m.media-amazon.com/images/M/MV5BZWU1ND...,"[Walter Hill (screenplay), Jim Thompson (novel)]",NaN
2991,573a1396f29313caabce5159,Lucienne Delamare and Pierre Maury are having ...,"[Crime, Drama, Thriller]",95.0,"[Stèphane Audran, Michel Piccoli, Claude Pièpl...",0,Wedding in Blood,Lucienne Delamare and Pierre Maury are having ...,[French],1973-04-12,...,"{'wins': 1, 'nominations': 1, 'text': '1 win &...",2015-08-21 00:01:43.923000000,1973,"{'rating': 7.3, 'votes': 945, 'id': 70453}","[France, Italy]",movie,"{'viewer': {'rating': 3.8, 'numReviews': 305, ...",https://m.media-amazon.com/images/M/MV5BNjNjM2...,"[Aeschylus (opening quotation), Claude Chabrol]",NaN
2999,573a1396f29313caabce5268,A black man plays Uncle Tom in order to gain a...,"[Action, Drama, Crime]",102.0,"[Lawrence Cook, Janet League, Paula Kelly, J.A...",0,The Spook Who Sat by the Door,In order to improve his standing with Black vo...,[English],1981-12-23,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-15 03:36:29.980000000,1973,"{'rating': 7.2, 'votes': 740, 'id': 70726}",[USA],movie,"{'viewer': {'rating': 3.9, 'numReviews': 1067,...",https://m.media-amazon.com/images/M/MV5BNDVmM2...,"[Sam Greenlee (screenplay), Melvin Clay (scree...",NaN
3059,573a1396f29313caabce577b,Inspector Clouseau is put on the case when the...,"[Comedy, Crime, Mystery]",113.0,"[Peter Sellers, Christopher Plummer, Catherine...",0,The Return of the Pink Panther,"That famous jewel, The Pink Panther, has once ...",[English],1975-05-21,...,"{'wins': 5, 'nominations': 2, 'text': 'Nominat...",2015-08-19 00:46:50.937000000,1975,"{'rating': 7.1, 'votes': 18310, 'id': 72081}",[UK],movie,"{'viewer': {'rating': 3.4, 'numReviews': 41317...",https://m.media-amazon.com/images/M/MV5BMTM2OD...,"[Frank Waldman (screenplay), Blake Edwards (sc...",NaN
3198,573a1397f29313caabce5fae,A detective (inspector Rogas) is assigned to i...,"[Crime, Thriller, Mystery]",120.0,"[Lino Ventura, Tino Carraro, Marcel Bozzuffi, ...",1,Illustrious Corpses,A detective (inspector Rogas) is assigned to i...,[Italian],1976-02-12,...,"{'wins': 5, 'nominations': 6, 'text': '5 wins ...",2015-07-12 00:31:06.280000000,1976,"{'rating': 7.4, 'votes': 1067, 'id': 74262}","[Italy, France]",movie,"{'viewer': {'rating': 3.7, 'numReviews': 399, ...",https://m.media-amazon.com/images/M/MV5BOTY2NG...,"[Francesco Rosi (screenplay), Tonino Guerra (s...",NaN
3280,573a1397f29313caabce62a4,Charles Dreyfus threatens to destroy the world...,"[Comedy, Crime, Thriller]",103.0,"[Peter Sellers, Herbert Lom, Lesley-Anne Down,...",0,The Pink Panther Strikes Again,Charles Dreyfus escapes from the mental asylum...,[English],1976-12-15,...,"{'wins': 3, 'nominations': 2, 'text': 'Nominat...",2015-09-15 04:11:57.200000000,1976,"{'rating': 7.2, 'votes': 20769, 'id': 75066}","[UK, USA]",movie,"{'viewer': {'rating': 3.4, 'numReviews': 37731...",https://m.media-amazon.com/images/M/MV5BZjhiND...,"[Frank Waldman (screenplay), Blake Edwards (sc...",NaN
3342,573a1397f29313caabce6681,"Belle Duke, in order to get revenge on her for...","[Comedy, Crime]",105.0,"[Adriano Celentano, Anthony Quinn, Capucine, U...",0,High Rollers,"Belle Duke, in order to get revenge on her for...",[Italian],1981-04-01,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-17 04:41:25.397000000,1976,"{'rating': 7.6, 'votes': 1679, 'id': 76101}",[Italy],movie,"{'viewer': {'rating': 1.6, 'numReviews': 19}, ...",https://m.media-amazon.com/images/M/MV5BZDYwYW...,"[Massimo De Rita (screenplay), Sergio Corbucci...",NaN
3458,573a1397f29313caabce6b68,As Hercule Poirot enjoys a luxurious cruise do...,"[Crime, Drama, Mystery]",140.0,"[Peter Ustinov, Jane Birkin, Lois Chiles, Bett...",0,Death on the Nile,"Almost everyone on the S.S.Karnak, cruising th...","[English, French, Arabic, German]",1978-09-29,...,"{'wins': 5, 'nominations': 5, 'text': 'Won 1 O...",2015-09-12 00:32:17.430000000,1978,"{'rating': 7.2, 'votes': 18077, 'id': 77413}",[UK],movie,"{'viewer': {'rating': 3.5, 'numReviews': 8382,...",https://m.media-amazon.com/images/M/MV5BYzIwMz...,[Anthony Shaffer (screenplay)],NaN
3556,573a1397f29313caabce6cab,"In San Francisco, a group of people discover t...","[Horror, Sci-Fi]",115.0,"[Donald Sutherland, Brooke Adams, Jeff Goldblu...",0,Invasion of the Body Snatchers,The first remake of the paranoid infiltration ...,[English],1978-12-20,...,"{'wins': 4, 'nominations': 9, 'text': '4 wins ...",2015-09-13 00:04:16.797000000,1978,"{'rating': 7.4, 'votes': 34043, 'id': 77745}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 34353...",https://m.media-amazon.com/images/M/MV5BMTg1MT...,"[Jack Finney (novel), W.D. Richter (screenplay)]",NaN
3559,573a1397f29313caabce6ddc,NaN,"[Comedy, Crime]",109.0,"[Terence Hill, Bud Spencer, Luciano Catenacci,...",0,Trinity: Gambling for High Stakes,NaN,"[Italian, French]",1978-10-28,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-07-28 00:35:21.823000000,1978,"{'rating': 7.2, 'votes': 4323, 'id': 78058}",[Italy],movie,"{'viewer': {'rating': 2.4, 'numReviews': 589, ...",https://m.media-amazon.com/images/M/MV5BOWFiYW...,"[Mario Amendola (story), Bruno Corbucci (story...",NaN
3672,573a1397f29313caabce73ea,Jonathan and Lucy live in Wismar and the Count...,[Horror],107.0,"[Klaus Kinski, Isabelle Adjani, Bruno Ganz, Ro...",0,Nosferatu the Vampyre,Jonathan Harker is sent away to Count Dracula'...,"[German, English, Romany]",1979-01-17,...,"{'wins': 5, 'nominations': 8, 'text': '5 wins ...",2015-09-16 10:54:04.087000000,1979,"{'rating': 7.6, 'votes': 21537, 'id': 79641}","[West Germany, France]",movie,"{'viewer': {'rating': 3.8, 'numReviews': 20719...",https://m.media-amazon.com/images/M/MV5BNDYxYW...,[Werner Herzog],NaN
3740,573a1397f29313caabce7849,When a young boy's family is killed by the mob...,"[Crime, Drama, Thriller]",123.0,"[Julie Carmen, Tony Knesich, Gregory Cleghorne...",0,Gloria,Mild mannered Jack Dawn has been secretly work...,[English],1980-09-19,...,"{'wins': 5, 'nominations': 1, 'text': 'Nominat...",2015-08-24 00:40:38.993000000,1980,"{'rating': 7.1, 'votes': 5613, 'id': 80798}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 4591,...",https://m.media-amazon.com/images/M/MV5BODRiMD...,[John Cassavetes],NaN
3869,573a1397f29313caabce7eb7,"Kermit, Gonzo and Fozzie are reporters who tra...","[Comedy, Crime, Family]",95.0,"[Jim Henson, Frank Oz, Dave Goelz, Jerry Nelson]",0,The Great Muppet Caper,Kermit and Fozzie are newspaper reporters sent...,[English],1981-06-26,...,"{'wins': 0, 'nominations': 2, 'text': 'Nominat...",2015-09-03 00:29:12.240000000,1981,"{'rating': 7.2, 'votes': 9158, 'id': 82474}","[UK, USA]",movie,"{'viewer': {'rating': 3.4, 'numReviews': 35030...",https://m.media-amazon.com/images/M/MV5BYzViOW...,"[Tom Patchett, Jay Tarses, Jerry Juhl, Jack Rose]",NaN
4198,573a1397f29313caabce867c,A family's home is haunted by a host of ghosts.,[Horror],114.0,"[Craig T. Nelson, JoBeth Williams, Beatrice St...",0,Poltergeist,A young family are visited by ghosts in their ...,[English],1982-06-04,...,"{'wins': 7, 'nominations': 4, 'text': 'Nominat...",2015-09-07 00:17:55.617000000,1982,"{'rating': 7.4, 'votes': 94447, 'id': 84516}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 18076...",https://m.media-amazon.com/images/M/MV5BNzliZm...,"[Steven Spielberg (screenplay), Michael Grais ...",79.0
4421,573a1398f29313caabce913d,A boy inadvertantly breaks 3 important rules c...,"[Comedy, Horror]",106.0,"[Hoyt Axton, John Louie, Keye Luke, Don Steele]",1,Gremlins,Minature green monsters tear through the small...,"[English, Spanish]",1984-06-08,...,"{'wins': 7, 'nominations': 6, 'text': '7 wins ...",2015-09-05 00:00:44.033000000,1984,"{'rating': 7.2, 'votes': 125839, 'id': 87363}",[USA],movie,NaN,https://m.media-amazon.com/images/M/MV5BZDVjN2...,[Chris Columbus],NaN
4489,573a1398f29313caabce8e2a,Claude Massoulier is murdered while hunting at...,"[Comedy, Crime, Mystery]",110.0,"[Fanny Ardant, Jean-Louis Trintignant, Jean-Pi...",1,Confidentially Yours,Claude Massoulier is murdered while hunting at...,[French],1983-08-10,...,"{'wins': 0, 'nominations': 3, 'text': 'Nominat...",2015-08-13 00:40:02.003000000,1983,"{'rating': 7.4, 'votes': 3890, 'id': 86551}",[France],movie,NaN,https://m.media-amazon.com/images/M/MV5BOGFmYT...,"[Charles Williams (novel), Franèois Truffaut, ...",NaN
4680,573a1398f29313caabce944e,An African American officer investigates a mur...,"[Crime, Drama, Mystery]",101.0,"[Howard E. Rollins Jr., Adolph Caesar, Art Eva...",0,A Soldier's Story,A black soldier is killed while returning to h...,[English],1984-11-02,...,"{'wins': 8, 'nominations': 6, 'text': 'Nominat...",2015-08-13 01:03:34.567000000,1984,"{'rating': 7.2, 'votes': 6172, 'id': 88146}",[USA],movie,NaN,https://m.media-amazon.com/images/M/MV5BMzUxMj...,"[Charles Fuller (screenplay), Charles Fuller (...",NaN
4683,573a1398f29313caabce9497,A night at the movies turns into a nightmare w...,"[Short, Horror, Music]",13.0,"[Michael Jackson, Ola Ray, Vincent Price, Hana...",0,Michael Jackson: Thriller,Michael Jackson and his date are watching a mo...,[English],1983-12-02,...,"{'wins': 2, 'nominations': 0, 'text': '2 wins.'}",2015-09-11 00:43:01.960000000,1983,"{'rating': 8.6, 'votes': 10458, 'id': 88263}",[USA],movie,NaN,https://m.media-amazon.com/images/M/MV5BODhhZj...,"[John Landis, Michael Jackson]",NaN
4849,573a1398f29313caabce9ad0,Two Scottish friends become local folk heroes ...,"[Comedy, Crime]",90.0,"[Vincent Friell, Joe Mullaney, Teri Lally, Ned...",0,Restless Natives,Two lads in Edinburgh embark on a non-violent ...,[English],1986-09-12,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-07-22 00:53:21.047000000,1985,"{'rating': 7.2, 'votes': 912, 'id': 89904}",[UK],movie,NaN,https://m.media-amazon.com/images/M/MV5BYmQyMW...,[Ninian Dunnett],NaN
5278,573a1398f29313caabceae04,Two con men try to settle their rivalry by bet...,"[Comedy, Crime]",110.0,"[Steve Martin, Michael Caine, Glenne Headly, A...",1,Dirty Rotten Scoundrels,Lawrence and Freddie are con-men; big-time and...,[English],1988-12-14,...,"{'wins': 2, 'nominations': 0, 'text': 'Nominat...",2015-08-24 01:02:36.353000000,1988,"{'rating': 7.3, 'votes': 47252, 'id': 95031}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 48099...",https://m.media-amazon.com/images/M/MV5BMTYyND...,"[Dale Launer, Stanley Shapiro, Paul Henning]",68.0
5357,573a1398f29313caabceb35c,A toon hating detective is a cartoon rabbit's ...,"[Animation, Comedy, Crime]",104.0,"[Bob Hoskins, Christopher Lloyd, Joanna Cassid...",0,Who Framed Roger Rabbit,'Toon star Roger is worried that his wife Jess...,[English],1988-06-22,...,"{'wins': 22, 'nominations': 21, 'text': 'Won 3...",2015-09-13 00:26:06.120000000,1988,"{'rating': 7.7, 'votes': 127268, 'id': 96438}",[USA],movie,"{'viewer': {'rating': 3.5, 'numReviews': 44035...",https://m.media-amazon.com/images/M/MV5BMDhiOT...,"[Gary K. Wolf (novel), Jeffrey Price (screenpl...",83.0
9669,573a13a0f29313caabd04202,Jonathan and Lucy live in Wismar and the Count...,[Horror],107.0,"[Klaus Kinski, Isabelle Adjani, Bruno Ganz, Ro...",0,Nosferatu the Vampyre,Jonathan Harker is sent away to Count Dracula'...,"[German, English, Romany]",1979-01-17,...,"{'wins': 5, 'nominations': 8, 'text': '5 wins ...",2015-08-30 04:39:17.020000000,1979,"{'rating': 7.6, 'votes': 21413, 'id': 79641}","[West Germany, France]",movie,"{'viewer': {'rating': 3.8, 'numReviews': 20719...",https://m.media-amazon.com/images/M/MV5BNDYxYW...,[Werner Herzog],NaN

## Citibike Data

How many trips in the sample_training.trips collection started at stations that are to
the west of the -74 longitude coordinate?
Longitude decreases in value as you move west.

In [10]:
db = client.get_database('sample_training')
trips = db.trips.find()
trips_df = pd.DataFrame(trips)
trips_df

,_id,tripduration,start station id,start station name,end station id,end station name,bikeid,usertype,birth year,start station location,end station location,start time,stop time
0,572bb8222b288919b68abf5c,589,489,10 Ave & W 28 St,284,Greenwich Ave & 8 Ave,21997,Subscriber,1982,"{'type': 'Point', 'coordinates': [-74.00176802...","{'type': 'Point', 'coordinates': [-74.00263761...",2016-01-01 00:00:48,2016-01-01 00:10:37
1,572bb8222b288919b68abf61,1376,527,E 33 St & 2 Ave,259,South St & Whitehall St,23933,Subscriber,1963,"{'type': 'Point', 'coordinates': [-73.976056, ...","{'type': 'Point', 'coordinates': [-74.01234218...",2016-01-01 00:03:12,2016-01-01 00:26:09
2,572bb8222b288919b68abf63,615,432,E 7 St & Avenue A,311,Norfolk St & Broome St,23993,Subscriber,1971,"{'type': 'Point', 'coordinates': [-73.98379855...","{'type': 'Point', 'coordinates': [-73.98802084...",2016-01-01 00:03:43,2016-01-01 00:13:59
3,572bb8222b288919b68abf64,1770,3226,W 82 St & Central Park West,509,9 Ave & W 22 St,22541,Subscriber,1970,"{'type': 'Point', 'coordinates': [-73.97137, 4...","{'type': 'Point', 'coordinates': [-74.00197139...",2016-01-01 00:04:43,2016-01-01 00:34:14
4,572bb8222b288919b68abf6e,719,3116,Huron St & Franklin St,3126,44 Dr & Jackson Ave,16624,Subscriber,1982,"{'type': 'Point', 'coordinates': [-73.95826, 4...","{'type': 'Point', 'coordinates': [-73.9432635,...",2016-01-01 00:10:00,2016-01-01 00:21:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,572bb8232b288919b68b1c15,415,457,Broadway & W 58 St,3164,Columbus Ave & W 72 St,22736,Subscriber,1966,"{'type': 'Point', 'coordinates': [-73.98169333...","{'type': 'Point', 'coordinates': [-73.97898475...",2016-01-02 19:29:04,2016-01-02 19:35:59
9996,572bb8232b288919b68b1c1b,268,304,Broadway & Battery Pl,363,West Thames St,18736,Subscriber,1960,"{'type': 'Point', 'coordinates': [-74.01361706...","{'type': 'Point', 'coordinates': [-74.01713445...",2016-01-02 19:29:48,2016-01-02 19:34:16
9997,572bb8232b288919b68b1c27,1319,3235,E 41 St & Madison Ave,490,8 Ave & W 33 St,24227,Customer,,"{'type': 'Point', 'coordinates': [-73.97992193...","{'type': 'Point', 'coordinates': [-73.993934, ...",2016-01-02 19:30:19,2016-01-02 19:52:19
9998,572bb8232b288919b68b1c44,566,442,W 27 St & 7 Ave,380,W 4 St & 7 Ave S,15101,Subscriber,1988,"{'type': 'Point', 'coordinates': [-73.993915, ...","{'type': 'Point', 'coordinates': [-74.00293877...",2016-01-02 19:33:16,2016-01-02 19:42:42
9999,572bb8232b288919b68b1c48,552,438,St Marks Pl & 1 Ave,536,1 Ave & E 30 St,23575,Subscriber,1992,"{'type': 'Point', 'coordinates': [-73.98564945...","{'type': 'Point', 'coordinates': [-73.97536082...",2016-01-02 19:34:07,2016-01-02 19:43:19

In [11]:


trips_df[[point['coordinates'][0]<(-74) for point in trips_df['start station location']]].count()[0]

1928

What is the difference between the number of people born in 1998 and the number of
people born after 1998 in the sample_training.trips collection?

In [12]:
pd.DataFrame( [sum(trips_df['birth year'][trips_df['birth year']!='']>1998),sum(trips_df['birth year'][trips_df['birth year']!='']==1998)],index=['after 1998', 'at 1998'], columns=['Value'])

            Value
after 1998     18
at 1998        12