In [1]:
#build a Streamlit application, that allows exploration of the dataset.
#mongodb airbnb dataset.

#connect to mongodb
import streamlit as st
import pandas as pd
import numpy as np
import pymongo
import ssl
from pymongo import MongoClient


def load_data():
    client = MongoClient(
        'mongodb+srv://student:nRfKfRqEtgWvznFD@cluster0.gu4ru.mongodb.net')
    #load 100 entries
    db = client.get_database('sample_airbnb')

    data = pd.DataFrame(db.listingsAndReviews.find().limit(100))
    data["price"] = data.price.astype(str).astype(float)
    return data






#def render_info():
def render_info():
    st.title('Airbnb data')
    st.header('Displaying the airbnb dataset')
    st.markdown('Using streamlit to filter and display data fetched from a mongodb database.')

#get Coordinates (NOT USED) (Not working key error)???
def get_coordinates(data):
    coordinates = []
    copy_data = data.copy()
    for i in range(len(data)-1):
        #check if exits

        if copy_data['address'][i] != None:
            address = copy_data['address'][i]
            if address is not None:
                    point = (address['location'])
                    #print(point)
                    coordinates.append(point)

    return coordinates

#draw map
def render_map(data):
#    location    = get_coordinates(data)
    df_map      = pd.DataFrame([pd.Series(point['location']["coordinates"], index=['lon', 'lat']) for point in data["address"]], columns=['lon', 'lat'])
    st.map(df_map)

#make price slider
def filter_by_price(data):
    #adding a range slider, allowing to choose values in range 
    range = st.slider('Price', int(min(data['price'])), int(max(data['price'])), (20, 400))

    return data[(data['price'].between(*range))]

#filter by property_type
def filter_by_property_type(data):
    property_type = st.sidebar.selectbox('Filter by different property types:', [''] + list(data['property_type'].drop_duplicates()))
    if property_type:
        return data[data['property_type'] == property_type]
    return data







render_info()
data = load_data()
data1 = filter_by_price(data)
data1 = filter_by_property_type(data1)


print(data1)
render_map(data1)

2022-12-03 18:12:24.891
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\gabri\anaconda3\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

NameError: name 'render_map' is not defined

In [9]:
data

,_id,tripduration,start station id,start station name,end station id,end station name,bikeid,usertype,birth year,start station location,end station location,start time,stop time
0,572bb8222b288919b68abf5c,589,489,10 Ave & W 28 St,284,Greenwich Ave & 8 Ave,21997,Subscriber,1982,"{'type': 'Point', 'coordinates': [-74.00176802...","{'type': 'Point', 'coordinates': [-74.00263761...",2016-01-01 00:00:48,2016-01-01 00:10:37
1,572bb8222b288919b68abf61,1376,527,E 33 St & 2 Ave,259,South St & Whitehall St,23933,Subscriber,1963,"{'type': 'Point', 'coordinates': [-73.976056, ...","{'type': 'Point', 'coordinates': [-74.01234218...",2016-01-01 00:03:12,2016-01-01 00:26:09
2,572bb8222b288919b68abf63,615,432,E 7 St & Avenue A,311,Norfolk St & Broome St,23993,Subscriber,1971,"{'type': 'Point', 'coordinates': [-73.98379855...","{'type': 'Point', 'coordinates': [-73.98802084...",2016-01-01 00:03:43,2016-01-01 00:13:59
3,572bb8222b288919b68abf64,1770,3226,W 82 St & Central Park West,509,9 Ave & W 22 St,22541,Subscriber,1970,"{'type': 'Point', 'coordinates': [-73.97137, 4...","{'type': 'Point', 'coordinates': [-74.00197139...",2016-01-01 00:04:43,2016-01-01 00:34:14
4,572bb8222b288919b68abf6e,719,3116,Huron St & Franklin St,3126,44 Dr & Jackson Ave,16624,Subscriber,1982,"{'type': 'Point', 'coordinates': [-73.95826, 4...","{'type': 'Point', 'coordinates': [-73.9432635,...",2016-01-01 00:10:00,2016-01-01 00:21:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,572bb8232b288919b68b1c15,415,457,Broadway & W 58 St,3164,Columbus Ave & W 72 St,22736,Subscriber,1966,"{'type': 'Point', 'coordinates': [-73.98169333...","{'type': 'Point', 'coordinates': [-73.97898475...",2016-01-02 19:29:04,2016-01-02 19:35:59
9996,572bb8232b288919b68b1c1b,268,304,Broadway & Battery Pl,363,West Thames St,18736,Subscriber,1960,"{'type': 'Point', 'coordinates': [-74.01361706...","{'type': 'Point', 'coordinates': [-74.01713445...",2016-01-02 19:29:48,2016-01-02 19:34:16
9997,572bb8232b288919b68b1c27,1319,3235,E 41 St & Madison Ave,490,8 Ave & W 33 St,24227,Customer,,"{'type': 'Point', 'coordinates': [-73.97992193...","{'type': 'Point', 'coordinates': [-73.993934, ...",2016-01-02 19:30:19,2016-01-02 19:52:19
9998,572bb8232b288919b68b1c44,566,442,W 27 St & 7 Ave,380,W 4 St & 7 Ave S,15101,Subscriber,1988,"{'type': 'Point', 'coordinates': [-73.993915, ...","{'type': 'Point', 'coordinates': [-74.00293877...",2016-01-02 19:33:16,2016-01-02 19:42:42
9999,572bb8232b288919b68b1c48,552,438,St Marks Pl & 1 Ave,536,1 Ave & E 30 St,23575,Subscriber,1992,"{'type': 'Point', 'coordinates': [-73.98564945...","{'type': 'Point', 'coordinates': [-73.97536082...",2016-01-02 19:34:07,2016-01-02 19:43:19